name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd backend && npm ci

      - name: Build
        run: echo "Build backend"

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: honey123
          POSTGRES_DB: honey_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: honey_test
      DB_USER: postgres
      DB_PASSWORD: honey123
      DB_HOST: localhost
      DB_PORT: 5432
      JWT_SECRET: secret
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Create test database
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=honey123 psql -h localhost -U postgres -p 5432 -c "CREATE DATABASE honey_test;" || true

      - name: Sync database schema
        run: node backend/scripts/syncDb.js

      - name: Run backend tests
        run: cd backend && npm run test:coverage
