name: Honey Delivery CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: honey123
          POSTGRES_DB: honey_delivery
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: honey123
      DB_NAME: honey_test
      JWT_SECRET: testsecret

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd backend && npm ci

      - name: Create test database
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=honey123 psql -h localhost -U postgres -p 5432 -c "CREATE DATABASE honey_test;"

      - name: Run tests
        run: cd backend && npm run test:coverage

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Build frontend
        run: cd frontend && npm run build

      - name: Run frontend tests
        run: cd frontend && npm run test -- --coverage