name: Deploy

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/apps
            echo "stopping old containers gracefully..."
            docker compose --env-file .env.prod -f docker-compose.prod.yml stop || true

            echo "removing old containers"
            docker compose --env-file .env.prod -f docker-compose.prod.yml rm -f || true

            echo "pulling latest images..."
            docker compose --env-file .env.prod -f docker-compose.prod.yml pull

            echo "starting updated containers..."
            docker compose --env-file .env.prod -f docker-compose.prod.yml up -d